import { PropertyType, ListingStatus } from "./types.js";

export const ALL_AMENITIES = [
  { id: "parking", name: "Parking" },
  { id: "generator", name: "Generator" },
  { id: "security", name: "24/7 Security" },
  { id: "wifi", name: "WiFi" },
  { id: "pool", name: "Swimming Pool" },
  { id: "gym", name: "Gym" },
  { id: "ac", name: "Air Conditioning" },
  { id: "pet_friendly", name: "Pet Friendly" },
  { id: "furnished", name: "Furnished" },
];

export const MOCK_PROPERTIES = [
  {
    id: "prop-1",
    title: "Modern Downtown Apartment",
    type: PropertyType.Apartment,
    price: 250000,
    period: "year",
    address: "123 Main St, Lekki Phase 1",
    city: "Lagos",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    images: [
      "https://picsum.photos/seed/prop1-1/800/600",
      "https://picsum.photos/seed/prop1-2/800/600",
      "https://picsum.photos/seed/prop1-3/800/600",
      "https://picsum.photos/seed/prop1-4/800/600",
    ],
    description:
      "A beautifully designed modern apartment in the heart of the city. Comes with all modern amenities and a stunning view of the skyline. Perfect for young professionals.",
    amenities: ["Parking", "24/7 Security", "WiFi", "Air Conditioning"],
    status: ListingStatus.Available,
    isFeatured: true,
    isVerified: true,
    postedDate: "2024-07-20",
    agent: {
      id: "agent-1",
      name: "Jane Doe",
      avatar: "https://picsum.photos/seed/agent1/100/100",
      phone: "+234 801 234 5678",
    },
    reviews: [
      {
        id: "rev-1",
        author: "John Smith",
        avatar: "https://picsum.photos/seed/user1/100/100",
        rating: 5,
        comment: "Absolutely love this place! The agent was very helpful.",
        date: "2024-06-15",
      },
    ],
  },
  {
    id: "prop-2",
    title: "Cozy Mini-flat in a Serene Estate",
    type: PropertyType.MiniFlat,
    price: 150000,
    period: "year",
    address: "456 Serene Ave, Ikeja GRA",
    city: "Lagos",
    bedrooms: 1,
    bathrooms: 1,
    area: 750,
    images: [
      "https://picsum.photos/seed/prop2-1/800/600",
      "https://picsum.photos/seed/prop2-2/800/600",
    ],
    description:
      "A cozy and affordable mini-flat located in a very quiet and secure estate. Great for singles or young couples starting out.",
    amenities: ["Parking", "Generator", "24/7 Security"],
    status: ListingStatus.Available,
    isUrgent: true,
    postedDate: "2024-07-22",
    agent: {
      id: "agent-2",
      name: "Bayo Adekunle",
      avatar: "https://picsum.photos/seed/agent2/100/100",
      phone: "+234 802 345 6789",
    },
    reviews: [],
  },
  {
    id: "prop-3",
    title: "Spacious Commercial Shop on High Street",
    type: PropertyType.CommercialShop,
    price: 500000,
    period: "year",
    address: "789 High Street, Victoria Island",
    city: "Lagos",
    bedrooms: 0,
    bathrooms: 1,
    area: 2000,
    images: [
      "https://picsum.photos/seed/prop3-1/800/600",
      "https://picsum.photos/seed/prop3-2/800/600",
    ],
    description:
      "Prime commercial space with high foot traffic. Ideal for retail businesses, showrooms, or a high-end boutique. Features a large display window.",
    amenities: ["Parking"],
    status: ListingStatus.Available,
    isVerified: true,
    postedDate: "2024-07-18",
    agent: {
      id: "agent-3",
      name: "Properties Inc.",
      avatar: "https://picsum.photos/seed/agent3/100/100",
      phone: "+234 803 456 7890",
    },
    reviews: [],
  },
  {
    id: "prop-4",
    title: "Luxury 4-Bedroom Duplex with Pool",
    type: PropertyType.Duplex,
    price: 8500000,
    period: "year",
    address: "10 Palm Drive, Banana Island",
    city: "Lagos",
    bedrooms: 4,
    bathrooms: 5,
    area: 4500,
    images: [
      "https://picsum.photos/seed/prop4-1/800/600",
      "https://picsum.photos/seed/prop4-2/800/600",
      "https://picsum.photos/seed/prop4-3/800/600",
    ],
    description:
      "Experience luxury living in this exquisite 4-bedroom duplex. Features a private swimming pool, a gym, and state-of-the-art security systems.",
    amenities: [
      "Parking",
      "Generator",
      "24/7 Security",
      "Swimming Pool",
      "Gym",
      "Air Conditioning",
      "Pet Friendly",
    ],
    status: ListingStatus.Available,
    isFeatured: true,
    isVerified: true,
    postedDate: "2024-07-15",
    agent: {
      id: "agent-4",
      name: "Luxury Homes",
      avatar: "https://picsum.photos/seed/agent4/100/100",
      phone: "+234 804 567 8901",
    },
    reviews: [
      {
        id: "rev-2",
        author: "Chioma Nwosu",
        avatar: "https://picsum.photos/seed/user2/100/100",
        rating: 4,
        comment: "Beautiful property, although the access road can be busy.",
        date: "2024-07-01",
      },
    ],
  },
  {
    id: "prop-5",
    title: "Affordable Room Self-Contained",
    type: PropertyType.RoomSelfContained,
    price: 80000,
    period: "year",
    address: "22 University Rd, Yaba",
    city: "Lagos",
    bedrooms: 1,
    bathrooms: 1,
    area: 350,
    images: ["https://picsum.photos/seed/prop5-1/800/600"],
    description:
      "A decent and affordable room for a student or single individual. Close to major transport links and the university.",
    amenities: [],
    status: ListingStatus.Available,
    postedDate: "2024-07-23",
    agent: {
      id: "agent-2",
      name: "Bayo Adekunle",
      avatar: "https://picsum.photos/seed/agent2/100/100",
      phone: "+234 802 345 6789",
    },
    reviews: [],
  },
  {
    id: "prop-6",
    title: "Executive Office Space in Business Hub",
    type: PropertyType.OfficeSpace,
    price: 1200000,
    period: "year",
    address: "33 Business Plaza, Marina",
    city: "Lagos",
    bedrooms: 0,
    bathrooms: 2,
    area: 3000,
    images: [
      "https://picsum.photos/seed/prop6-1/800/600",
      "https://picsum.photos/seed/prop6-2/800/600",
    ],
    description:
      "Fully serviced office space in a prestigious business district. Includes conference rooms, high-speed internet, and a reception service.",
    amenities: [
      "Parking",
      "Generator",
      "24/7 Security",
      "WiFi",
      "Air Conditioning",
    ],
    status: ListingStatus.Available,
    isVerified: true,
    postedDate: "2024-07-10",
    agent: {
      id: "agent-3",
      name: "Properties Inc.",
      avatar: "https://picsum.photos/seed/agent3/100/100",
      phone: "+234 803 456 7890",
    },
    reviews: [],
  },
  {
    id: "prop-7",
    title: "Family-Friendly Full House",
    type: PropertyType.FullHouse,
    price: 2500000,
    period: "year",
    address: "15 Family Lane, Surulere",
    city: "Lagos",
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    images: [
      "https://picsum.photos/seed/prop7-1/800/600",
      "https://picsum.photos/seed/prop7-2/800/600",
    ],
    description:
      "A spacious and welcoming full house in a family-friendly neighborhood. Includes a private compound and a small garden.",
    amenities: ["Parking", "Pet Friendly"],
    status: ListingStatus.Available,
    postedDate: "2024-07-21",
    agent: {
      id: "agent-1",
      name: "Jane Doe",
      avatar: "https://picsum.photos/seed/agent1/100/100",
      phone: "+234 801 234 5678",
    },
    reviews: [],
  },
];
